const locations = {
  province: {
    P1: "San José",
    P2: "Alajuela",
    P3: "Cartago",
    P4: "Heredia",
    P5: "Guanacaste",
    P6: "Puntarenas",
    P7: "Limón",
  },
  canton: {
    P1: {
      C1: "San José",
      C2: "Escazú",
      C3: "Desamparados",
      C4: "Puriscal",
      C5: "Tarrazú",
      C6: "Aserrí",
      C7: "Mora",
      C8: "Goicoechea",
      C9: "Santa Ana",
      C10: "Alajuelita",
      C11: "Vázques de Coronado",
      C12: "Acosta",
      C13: "Tibás",
      C14: "Moravia",
      C15: "Montes de Oca",
      C16: "Turrubares",
      C17: "Dota",
      C18: "Curridabat",
      C19: "Pérez Zeledón",
      C20: "León Cortés",
    },
    P2: {
      C1: "Alajuela",
      C2: "San Ramón",
      C3: "Grecia",
      C4: "San Mateo",
      C5: "Atenas",
      C6: "Naranjo",
      C7: "Palmares",
      C8: "Poás",
      C9: "Orotina",
      C10: "San Carlos",
      C11: "Zarcero",
      C12: "Sarchí",
      C13: "Upala",
      C14: "Los Chiles",
      C15: "Guatuso",
      C16: "Río Cuarto",
    },
    P3: {
      C1: "Cartago",
      C2: "Paraíso",
      C3: "La Unión",
      C4: "Jiménez",
      C5: "Turrialba",
      C6: "Alvarado",
      C7: "Oreamuno",
      C8: "El Guarco",
    },
    P4: {
      C1: "Heredia",
      C2: "Barva",
      C3: "Santo Domingo",
      C4: "Santa Bárbara",
      C5: "San Rafael",
      C6: "San Isidro",
      C7: "Belén",
      C8: "Flores",
      C9: "San Pablo",
      C10: "Sarapiquí",
    },
    P5: {
      C1: "Liberia",
      C2: "Nicoya",
      C3: "Santa Cruz",
      C4: "Bagaces",
      C5: "Carrillo",
      C6: "Cañas",
      C7: "Abangares",
      C8: "Tilarán",
      C9: "Nandayure",
      C10: "La Cruz",
      C11: "Hojancha",
    },
    P6: {
      C1: "Puntarenas",
      C2: "Esparza",
      C3: "Buenos Aires",
      C4: "Montes de Oro",
      C5: "Osa",
      C6: "Quepos",
      C7: "Golfito",
      C8: "Coto Brus",
      C9: "Parrita",
      C10: "Corredores",
      C11: "Garabito",
    },
    P7: {
      C1: "Limón",
      C2: "Pococí",
      C3: "Siquirres",
      C4: "Talamanca",
      C5: "Matina",
      C6: "Guácimo",
    },
  },
  district: {
    P1: {
      C1: {
        D1: "Carmen",
        D2: "Merced",
        D3: "Hospital",
        D4: "Catedral",
        D5: "Zapote",
        D6: "San Francisco de Dos Ríos",
        D7: "La Uruca",
        D8: "Mata Redonda",
        D9: "Pavas",
        D10: "Hatillo",
        D11: "San Sebastián",
      },
      C2: {
        D1: "Escazú",
        D2: "San Antonio",
        D3: "San Rafael",
      },
      C3: {
        D1: "Desamparados",
        D2: "San Miguel",
        D3: "San Juan de Dios",
        D4: "San Rafael Arriba",
        D5: "San Antonio",
        D6: "Frailes",
        D7: "Patarrá",
        D8: "San Cristóbal",
        D9: "Rosario",
        D10: "Damas",
        D11: "San Rafael Abajo",
        D12: "Gravilias",
        D13: "Los Guido",
      },
      C4: {
        D1: "Santiago",
        D2: "Mercedes Sur",
        D3: "Barbacoas",
        D4: "Grifo Alto",
        D5: "San Rafael",
        D6: "Candelarita",
        D7: "Desamparaditos",
        D8: "San Antonio",
        D9: "Chires",
      },
      C5: {
        D1: "San Marcos",
        D2: "San Lorenzo",
        D3: "San Carlos",
      },
      C6: {
        D1: "Aserrí",
        D2: "Tarbaca",
        D3: "Vuelta de Jorco",
        D4: "San Gabriel",
        D5: "Legua",
        D6: "Monterrey",
        D7: "Salitrillos",
      },
      C7: {
        D1: "Colón",
        D2: "Guayabo",
        D3: "Tabarcia",
        D4: "Piedras Negras",
        D5: "Picagres",
        D6: "Jaris",
        D7: "Quitirrisí",
      },
      C8: {
        D1: "Guadalupe",
        D2: "San Fransisco",
        D3: "Calle Blancos",
        D4: "Mata de Plátano",
        D5: "Ipís",
        D6: "Rancho Redondo",
        D7: "Purral",
      },
      C9: {
        D1: "Santa Ana",
        D2: "Salitral",
        D3: "Pozos",
        D4: "Uruca",
        D5: "Piedades",
        D6: "Brasil",
      },
      C10: {
        D1: "Alajuelita",
        D2: "San Josecito",
        D3: "San Antonio",
        D4: "Concepción",
        D5: "San Felipe",
      },
      C11: {
        D1: "San Isidro",
        D2: "San Rafael",
        D3: "Dulce Nombre de Jesús",
        D4: "Platanillo",
        D5: "Cascajal",
      },
      C12: {
        D1: "San Igancio",
        D2: "Guaitil",
        D3: "Palmichal",
        D4: "Cangrejal",
        D5: "Sabanillas",
      },
      C13: {
        D1: "San Juan",
        D2: "Cinco Esquinas",
        D3: "Anselmo Llorente",
        D4: "León XIII",
        D5: "Colima",
      },
      C14: {
        D1: "San Vicente",
        D2: "San Jerónimo",
        D3: "La Trinidad",
      },
      C15: {
        D1: "San Pedro",
        D2: "Sabanilla",
        D3: "Mercedes",
        D4: "San Rafael",
      },
      C16: {
        D1: "San Pablo",
        D2: "San Pedro",
        D3: "San Juan de Mata",
        D4: "San Luis",
        D5: "Carara",
      },
      C17: {
        D1: "Santa María",
        D2: "Jardín",
        D3: "Copey",
      },
      C18: {
        D1: "Curridabat",
        D2: "Granadilla",
        D3: "Sánchez",
        D4: "Tirrases",
      },
      C19: {
        D1: "San Isidro del General",
        D2: "El General",
        D3: "Daniel Flores",
        D4: "Rivas",
        D5: "San Pedro",
        D6: "Platanares",
        D7: "Pejibaye",
        D8: "Cajón",
        D9: "Barú",
        D10: "Río Nuevo",
        D11: "Páramo",
        D12: "La Amistad",
      },
      C20: {
        D1: "San Pablo",
        D2: "San Andrés",
        D3: "Llano Bonito",
        D4: "San Isidro",
        D5: "Santa Cruz",
        D6: "San Antonio",
      },
    },
    P2: {
      C1: {
        D1: "Alajuela",
        D2: "San José",
        D3: "Carrizal",
        D4: "San Antonio",
        D5: "Guácima",
        D6: "San Isidro",
        D7: "Sabanilla",
        D8: "San Rafael",
        D9: "Río Segundo",
        D10: "Desamparados",
        D11: "Turrúcares",
        D12: "Tambor",
        D13: "La Garita",
        D14: "Sarapiquí",
      },
      C2: {
        D1: "San Ramón",
        D2: "Santiago",
        D3: "San Juan",
        D4: "Piedades Norte",
        D5: "Piedades Sur",
        D6: "San Rafael",
        D7: "San Isidro",
        D8: "Ángeles",
        D9: "Alfaro",
        D10: "Volio",
        D11: "Concepción",
        D12: "Zapotal",
        D13: "Peñas Blancas",
        D14: "San Lorenzo",
      },
      C3: {
        D1: "Grecia",
        D2: "San Isidro",
        D3: "San José",
        D4: "San Roque",
        D5: "Tacares",
        D6: "Puente de Piedra",
        D7: "Bolívar",
      },
      C4: {
        D1: "San Mateo",
        D2: "Desmonte",
        D3: "Jesús María",
        D4: "Labrador",
      },
      C5: {
        D1: "Atenas",
        D2: "Jesús",
        D3: "Mercedes",
        D4: "San Isidro",
        D5: "Concepción",
        D6: "San José",
        D7: "Santa Eulalia",
        D8: "Escobal",
      },
      C6: {
        D1: "Naranjo",
        D2: "San Miguel",
        D3: "San José",
        D4: "Cirrí Sur",
        D5: "San Jerónimo",
        D6: "San Juan",
        D7: "El Rosario",
        D8: "Palmitos",
      },
      C7: {
        D1: "Palmares",
        D2: "Zaragoza",
        D3: "Buenos Aires",
        D4: "Santiago",
        D5: "Candelaria",
        D6: "Esquipulas",
        D7: "La Granja",
      },
      C8: {
        D1: "San Pedro",
        D2: "San Juan",
        D3: "San Rafael",
        D4: "Carrillos",
        D5: "Sabana Redonda",
      },
      C9: {
        D1: "Orotina",
        D2: "El Mastate",
        D3: "Hacienda Vieja",
        D4: "Coyolar",
        D5: "La Ceiba",
      },
      C10: {
        D1: "Quesada",
        D2: "Florencia",
        D3: "Buena Vista",
        D4: "Aguas Zarcas",
        D5: "Venecia",
        D6: "Pital",
        D7: "La Fortuna",
        D8: "La Tigra",
        D9: "La Palmera",
        D10: "Venado",
        D11: "Cutris",
        D12: "Monterrey",
        D13: "Pocosol",
      },
      C11: {
        D1: "Zarcero",
        D2: "Laguna",
        D3: "Tapesco",
        D4: "Guadalupe",
        D5: "Palmira",
        D6: "Zapote",
        D7: "Brisas",
      },
      C12: {
        D1: "Sarchí Norte",
        D2: "Sarchí Sur",
        D3: "Toro Amarillo",
        D4: "San Pedro",
        D5: "Rodríguez",
      },
      C13: {
        D1: "Upala",
        D2: "Aguas Claras",
        D3: "San José (Pizote)",
        D4: "Bijagua",
        D5: "Delicias",
        D6: "Dos Ríos",
        D7: "Yolillal",
        D8: "Canalete",
      },
      C14: {
        D1: "Los Chiles",
        D2: "Caño Negro",
        D3: "El Amparo",
        D4: "San Jorge",
      },
      C15: {
        D1: "San Rafael",
        D2: "Buenavista",
        D3: "Cote",
        D4: "Katira",
      },
      C16: {
        D1: "Río Cuarto",
        D2: "Santa Rita",
        D3: "Santa Isabel",
      },
    },
    P3: {
      C1: {
        D1: "Oriental",
        D2: "Occidental",
        D3: "Carmen",
        D4: "San Nicolás",
        D5: "Agua Caliente",
        D6: "Guadalupe",
        D7: "Corralillo",
        D8: "Tierra Blanca",
        D9: "Dulce Nombre",
        D10: "Llano Grande",
        D11: "Quebradilla",
      },
      C2: {
        D1: "Paraíso",
        D2: "Santiago",
        D3: "Orosi",
        D4: "Cachí",
        D5: "Llanos de Santa Lucía",
      },
      C3: {
        D1: "Tres Ríos",
        D2: "San Diego",
        D3: "San Juan",
        D4: "San Rafael",
        D5: "Concepción",
        D6: "Dulce Nombre",
        D7: "San Ramón",
        D8: "Río Azul",
      },
      C4: {
        D1: "Juan Viñas",
        D2: "Tucurrique",
        D3: "Pejibaye",
      },
      C5: {
        D1: "Turrialba",
        D2: "La Suiza",
        D3: "Peralta",
        D4: "Santa Cruz",
        D5: "Santa Teresita",
        D6: "Pavones",
        D7: "Tuis",
        D8: "Tayutic",
        D9: "Santa Rosa",
        D10: "Tres Equis",
        D11: "La Isabel",
        D12: "Chirripó",
      },
      C6: {
        D1: "Pacayas",
        D2: "Cervantes",
        D3: "Capellanes",
      },
      C7: {
        D1: "San Rafael",
        D2: "Cot",
        D3: "Potrero Cerrado",
        D4: "Cipreses",
        D5: "Santa Rosa",
      },
      C8: {
        D1: "El Tejar",
        D2: "San Isidro",
        D3: "Tobosi",
        D4: "Patio de Agua",
      },
    },
    P4: {
      C1: {
        D1: "Heredia",
        D2: "Mercedes",
        D3: "San Francisco",
        D4: "Ulloa",
        D5: "Varablanca",
      },
      C2: {
        D1: "Barva",
        D2: "San Pedro",
        D3: "San Pablo",
        D4: "San Roque",
        D5: "Santa Lucia",
        D6: "San José de la Montaña",
      },
      C3: {
        D1: "Santo Domingo",
        D2: "San Vicente",
        D3: "San Miguel",
        D4: "Paracito",
        D5: "Santo Tomás",
        D6: "Santa Rosa",
        D7: "Tures",
        D8: "Pará",
      },
      C4: {
        D1: "Santa Bárbara",
        D2: "San Pedro",
        D3: "San Juan",
        D4: "Jesús",
        D5: "Santo Domingo",
        D6: "Purabá",
      },
      C5: {
        D1: "San Rafael",
        D2: "San Josecito",
        D3: "Santiago",
        D4: "Ángeles",
        D5: "Concepción",
      },
      C6: {
        D1: "San Isidro",
        D2: "San José",
        D3: "Concepción",
        D4: "San José",
      },
      C7: {
        D1: "San Antonio",
        D2: "La Ribiera",
        D3: "La Asunción",
      },
      C8: {
        D1: "San Joaquín",
        D2: "Barrantes",
        D3: "Llorente",
      },
      C9: {
        D1: "San Pablo",
        D2: "Rincón de Sabanilla",
      },
      C10: {
        D1: "Puerto Viejo",
        D2: "La Virgen",
        D3: "Horquetas",
        D4: "Llanuras del Gaspar",
        D5: "Cureña",
      },
    },
    P5: {
      C1: {
        D1: "Liberia",
        D2: "Cañas Dulces",
        D3: "Mayorga",
        D4: "Nacascolo",
        D5: "Curubandé",
      },
      C2: {
        D1: "Nicoya",
        D2: "Mansión",
        D3: "San Antonio",
        D4: "Querbada Honda",
        D5: "Sámara",
        D6: "Nosara",
        D7: "Belén de Nosarita",
      },
      C3: {
        D1: "Santa Cruz",
        D2: "Bolsón",
        D3: "Veintisiete de Abril",
        D4: "Tempate",
        D5: "Cartagena",
        D6: "Cuajiniquil",
        D7: "Diriá",
        D8: "Cabo Velas",
        D9: "Tamarindo",
      },
      C4: {
        D1: "Bagaces",
        D2: "La Fortuna",
        D3: "Mogote",
        D4: "Río Naranjo",
      },
      C5: {
        D1: "Filadelfia",
        D2: "Palmira",
        D3: "Sardinal",
        D4: "Belén",
      },
      C6: {
        D1: "Cañas",
        D2: "Palmira",
        D3: "San Miguel",
        D4: "Bebedero",
        D5: "Porozal",
      },
      C7: {
        D1: "Las Juntas",
        D2: "Sierra",
        D3: "San Juan",
        D4: "Colorado",
      },
      C8: {
        D1: "Tilarán",
        D2: "Quebrada Grande",
        D3: "Tronadora",
        D4: "Santa Rosa",
        D5: "Líbano",
        D6: "Tierras Morenas",
        D7: "Arenal",
        D8: "Cabeceras",
      },
      C9: {
        D1: "Carmona",
        D2: "Santa Rita",
        D3: "Zapotal",
        D4: "San Pablo",
        D5: "Porvenir",
        D6: "Bejuco",
      },
      C10: {
        D1: "La Cruz",
        D2: "Santa Cecilia",
        D3: "La Garita",
        D4: "Santa Elena",
      },
      C11: {
        D1: "Hojancha",
        D2: "Monte Romo",
        D3: "Puerto Carrillo",
        D4: "Huacas",
        D5: "Matambú",
      },
    },
    P6: {
      C1: {
        D1: "Puntarenas",
        D2: "Pitahaya",
        D3: "Chomes",
        D4: "Lepanto",
        D5: "Paquera",
        D6: "Manzanillo",
        D7: "Guacimal",
        D8: "Barranca",
        D9: "Monteverde",
        D10: "Isla del Coco",
        D11: "Cóbano",
        D12: "Chacarita",
        D13: "Chira",
        D14: "Acapulco",
        D15: "El Roble",
        D16: "Arancibia",
      },
      C2: {
        D1: "Espíritu Santo",
        D2: "San Juan Grande",
        D3: "Macacona",
        D4: "San Rafael",
        D5: "San Jerónimo",
        D6: "Caldera",
      },
      C3: {
        D1: "Buenos Aires",
        D2: "Volcán",
        D3: "Potrero Grande",
        D4: "Boruca",
        D5: "Pilas",
        D6: "Colinas",
        D7: "Chánguena",
        D8: "Biolley",
        D9: "Brunka",
      },
      C4: {
        D1: "Miramar",
        D2: "La Unión",
        D3: "San Isidro",
      },
      C5: {
        D1: "Puerto Cortés",
        D2: "Palmar",
        D3: "Sierpe",
        D4: "Bahía Ballena",
        D5: "Piedras Blancas",
        D6: "Bahía Drake",
      },
      C6: {
        D1: "Quepos",
        D2: "Savegre",
        D3: "Naranjito",
      },
      C7: {
        D1: "Golfito",
        D2: "Puerto Jiménez",
        D3: "Guaycará",
        D4: "Pavón",
      },
      C8: {
        D1: "San Vito",
        D2: "Sabalito",
        D3: "Aguabuena",
        D4: "Limoncito",
        D5: "Pittier",
        D6: "Gutiérrez Braun",
      },
      C9: {
        D1: "Parrita",
      },
      C10: {
        D1: "Corredor",
        D2: "La Cuesta",
        D3: "Canoas",
        D4: "Laurel",
      },
      C11: {
        D1: "Jacó",
        D2: "Tárcoles",
      },
    },
    P7: {
      C1: {
        D1: "Limón",
        D2: "Valle la Estrella",
        D3: "Río Blanco",
        D4: "Matamba",
      },
      C2: {
        D1: "Guápiles",
        D2: "Jiménez",
        D3: "La Rita",
        D4: "Roxana",
        D5: "Cariari",
        D6: "Colorado",
        D7: "La Colonia",
      },
      C3: {
        D1: "Siquirres",
        D2: "Pacuarito",
        D3: "Florida",
        D4: "Germania",
        D5: "El Cairo",
        D6: "Alegría",
        D7: "Reventazón",
      },
      C4: {
        D1: "Bratsi",
        D2: "Sixaola",
        D3: "Cahuita",
        D4: "Telire",
      },
      C5: {
        D1: "Matina",
        D2: "Batán",
        D3: "Carrandi",
      },
      C6: {
        D1: "Guácimo",
        D2: "Mercedes",
        D3: "Pocora",
        D4: "Río Jiménez",
        D5: "Duacari",
      },
    },
  },
};

export { locations };
