const locations = {
  province: {
    P1: "San José",
    P2: "Alajuela",
    P3: "Cartago",
    P4: "Heredia",
    P5: "Guanacaste",
    P6: "Puntarenas",
    P7: "Limón",
  },
  canton: {
    P1: {
      C1: "San José",
      C2: "Escazú",
      C3: "Desamparados",
      C4: "Puriscal",
      C5: "Tarrazú",
      C6: "Aserrí",
      C7: "Mora",
      C8: "Goicoechea",
      C9: "Santa Ana",
      C10: "Alajuelita",
      C11: "Vázques de Coronado",
      C12: "Acosta",
      C13: "Tibás",
      C14: "Moravia",
      C15: "Montes de Oca",
      C16: "Turrubares",
      C17: "Dota",
      C18: "Curridabat",
      C19: "Pérez Zeledón",
      C20: "León Cortés",
    },
    P2: {
      C1: "Alajuela",
    },
    P3: {
      C1: "Cartago",
    },
    P4: {
      C1: "Heredia",
    },
    P5: {
      C1: "Liberia",
    },
    P6: {
      C1: "Puntarenas",
    },
    P7: {
      C1: "Limón",
    },
  },
  district: {
    P1: {
      C1: {
        D1: "Carmen",
        D2: "Merced",
        D3: "Hospital",
        D4: "Catedral",
        D5: "Zapote",
        D6: "San Francisco de Dos Ríos",
        D7: "La Uruca",
        D8: "Mata Redonda",
        D9: "Pavas",
        D10: "Hatillo",
        D11: "San Sebastián",
      },
      C2: {
        D1: "Escazú",
        D2: "San Antonio",
        D3: "San Rafael",
      },
      C3: {
        D1: "Desamparados",
        D2: "San Miguel",
        D3: "San Juan de Dios",
        D4: "San Rafael Arriba",
        D5: "San Antonio",
        D6: "Frailes",
        D7: "Patarrá",
        D8: "San Cristóbal",
        D9: "Rosario",
        D10: "Damas",
        D11: "San Rafael Abajo",
        D12: "Gravilias",
        D13: "Los Guido",
      },
      C4: {
        D1: "Santiago",
        D2: "Mercedes Sur",
        D3: "Barbacoas",
        D4: "Grifo Alto",
        D5: "San Rafael",
        D6: "Candelarita",
        D7: "Desamparaditos",
        D8: "San Antonio",
        D9: "Chires",
      },
      C5: {
        D1: "San Marcos",
        D2: "San Lorenzo",
        D3: "San Carlos",
      },
      C6: {
        D1: "Aserrí",
        D2: "Tarbaca",
        D3: "Vuelta de Jorco",
        D4: "San Gabriel",
        D5: "Legua",
        D6: "Monterrey",
        D7: "Salitrillos",
        D8: "Colón",
        D9: "Guayabo",
        D10: "Tabarcia",
        D11: "Piedras Negras",
        D12: "Picagres",
        D12: "Jaris",
        D12: "Quitirrisí",
      },
      C7: {},
      C8: {},
      C9: {},
      C10: {},
      C11: {},
      C12: {},
      C13: {},
      C14: {},
      C15: {},
      C16: {},
      C17: {},
      C18: {},
      C19: {},
      C20: {},
    },
  },
};

export { locations };
